services:
  elibrary:
    image: "elibrary"
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - ./books:/elibrary/books
      - ./covers:/elibrary/covers
      - ./database.db:/elibrary/database.db
      - ./books.xlsx:/elibrary/books.xlsx
      - ./setup.sql:/elibrary/setup.sql