version: "3.4"

services:
  elibrary:
    image: deemp/elibrary:latest
    pull_policy: always
    ports:
      - "5000:5000"
      - "5001:5001"
    entrypoint:
      - "bash"
      - "-c"
    env_file:
      - back/.env.development
      - front/.env.development
    command:
      - |
        cd elibrary
        ln -s /dependencies/back/static/front back/static/front
        ln -s /dependencies/.venv .venv
        ln -s /dependencies/front/node_modules front/node_modules
        devFrontRun &
        devBackRun
    volumes:
      - ./back/__init__.py:/elibrary/back/__init__.py
      - ./back/internal:/elibrary/back/internal
      - ./back/main.py:/elibrary/back/main.py
      - ./back/routers:/elibrary/back/routers
      - ./back/static:/elibrary/back/static
      - ./back/tests:/elibrary/back/tests
      - ./books:/elibrary/books
      - ./books.xlsx:/elibrary/books.xlsx
      - ./covers:/elibrary/covers
      - ./development.db:/elibrary/development.db
      - ./development.sql:/elibrary/development.sql
      - ./front/index.html:/elibrary/front/index.html
      - ./front/package.json:/elibrary/front/package.json
      - ./front/public/vite.svg:/elibrary/front/public/vite.svg
      - ./front/src:/elibrary/front/src
      - ./front/tsconfig.json:/elibrary/front/tsconfig.json
      - ./front/tsconfig.node.json:/elibrary/front/tsconfig.node.json
      - ./front/vite.config.ts:/elibrary/front/vite.config.ts
      - ./poetry.toml:/elibrary/poetry.toml
      - ./pyproject.toml:/elibrary/pyproject.toml