version: "3.4"

services:
  elibrary:
    image: deemp/elibrary:latest
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      APP_NAME: "app-elibrary"
      PORT: 5000
      HOST: "0.0.0.0"
    entrypoint:
      - "bash"
      - "-c"
    command:
      - |
        cd elibrary
        ln -s /dependencies/back/static/front back/static/front
        ln -s /dependencies/.venv .venv
        ln -s /dependencies/front/node_modules front/node_modules
        runFront &
        runProd
    volumes:
      - ./back/internal:/elibrary/back/internal
      - ./back/routers:/elibrary/back/routers
      - ./back/static:/elibrary/back/static
      - ./back/tests:/elibrary/back/tests
      - ./back/__init__.py:/elibrary/back/__init__.py
      - ./back/.env.development:/elibrary/back/.env
      - ./back/auth.env:/elibrary/back/auth.env
      - ./back/log_conf.yaml:/elibrary/back/log_conf.yaml
      - ./back/main.py:/elibrary/back/main.py
      - ./books:/elibrary/books
      - ./covers:/elibrary/covers
      - ./poetry.toml:/elibrary/poetry.toml
      - ./pyproject.toml:/elibrary/pyproject.toml
      - ./database.db:/elibrary/database.db
      - ./books.xlsx:/elibrary/books.xlsx
      - ./front/public/vite.svg:/elibrary/front/public/vite.svg
      - ./front/.env.development:/elibrary/front/.env.development
      - ./front/package.json:/elibrary/front/package.json
      - ./front/tsconfig.json:/elibrary/front/tsconfig.json
      - ./front/tsconfig.node.json:/elibrary/front/tsconfig.node.json
      - ./front/vite.config.ts:/elibrary/front/vite.config.ts
      - ./front/index.html:/elibrary/front/index.html
      - ./front/src:/elibrary/front/src