@startuml dynamic

participant Client
participant FrontEnd
participant BackEnd
participant SSO
participant Database

Client -> FrontEnd : Open search in browser
activate Client
activate FrontEnd
FrontEnd -> BackEnd : Get /search
activate BackEnd
BackEnd -> SSO : Login
activate SSO
SSO -> BackEnd : Successful login
deactivate SSO
BackEnd -> Database : Request books
activate Database
Database -> BackEnd : Query books
deactivate Database
BackEnd -> FrontEnd : List of book to show
deactivate BackEnd
FrontEnd -> Client : Show list of books
deactivate FrontEnd
deactivate Client

Client -> FrontEnd : Open bookreader in browser
activate Client
activate FrontEnd
FrontEnd -> BackEnd : Get /book/{book_id}/file
activate BackEnd
BackEnd -> SSO : Login
activate SSO
SSO -> BackEnd : Successful login
deactivate SSO
BackEnd -> Storage : Request book file
activate Storage
Storage -> BackEnd : Send book file
deactivate Storage
BackEnd -> FrontEnd : Send book file
deactivate BackEnd
FrontEnd -> Client : Show book in bookreader
deactivate FrontEnd
deactivate Client

@enduml