@startuml static

package Client {
  object User {
  }
}

package FrontEnd {
  object "/" as FEIndex {
    context: Context
  }
}

package BackEnd {
  object "/search" as BESearch {
    bisac : String
    lc : String
    additional-filter : Optional <String, String>
  }
  object "/book/{book_id}" as BEBook {
    book : Book
  }
  object "/book/{book_id}/file" as BEBookreader {
    book : Book
  }
}

package SSO {
  object SSODatabase {
  }
}

package Database {
  object "Book" as TableBook {
  }
  object "User" as TableUser {
  }
}

package Storage {
  object "Book File" as FileBook {
  }
}

Client -- FrontEnd : Connect through browser
FrontEnd -- BackEnd : Interaction
BackEnd -- SSO : Authentication
BackEnd -- Database : Book and User info storage
BackEnd -- Storage : Book file storage

@enduml